name: build
on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  SAMO_DOCKER_REGISTRY: ghcr.io
  SAMO_DOCKER_GROUP: ${{ github.repository_owner }}/

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - uses: lorislab/install-samo-action@v1          
      - id: project_version
        run: echo "stdout=$(samo project version)" >> $GITHUB_OUTPUT
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.SAMO_DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build project
        run: |
          yq -iP '.version="${{ steps.project_version.outputs.stdout }}"' package.json -o json
          pnpm install --frozen-lockfile
          pnpm build
      - name: Build docker image
        run: samo project docker build -v debug
      - name: Push docker image
        run: samo project docker push -v debug        
      - name: Build helm
        run: samo project helm build -v debug
      - name: Push helm
        run: samo project helm push --helm-registry oci://${{ env.SAMO_DOCKER_REGISTRY }}/${{ github.repository_owner }}/charts -v debug


