name: build
on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_PAT }}
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Project version
        id: project_version
        uses: lorislab/samo-action@v1.0.0
        with:
          args: samo project version
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build project
        run: |
          yq -iP '.version="${{ steps.project_version.outputs.stdout }}"' package.json -o json
          npm ci

