name: build
on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  REGISTRY: ghcr.io
  NAME: todo-ui

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_PAT }}
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Project version
        id: project_version
        uses: lorislab/samo-action@v1.0.0
        with:
          args: samo project version
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build project
        run: |
          yq -iP '.version="${{ steps.project_version.outputs.stdout }}"' package.json -o json
          pnpm install --frozen-lockfile
          pnpm build
      - name: Build docker image
        run: |
          docker build -t ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.NAME }}:${{ steps.project_version.outputs.stdout }} -f docker/Dockerfile .
          docker push ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.NAME }}:${{ steps.project_version.outputs.stdout }}
      - name: Build helm
        run: |
          yq -iP '.version="${{ steps.project_version.outputs.stdout }}"' helm/Chart.yaml
          yq -iP '.image.tag="${{ steps.project_version.outputs.stdout }}"' helm/values.yaml
          helm package helm
          PKG_NAME=`ls *.tgz`
          helm push ${PKG_NAME} oci://${{ env.REGISTRY }}/${{ github.repository_owner }}/charts

