name: release
on:
  push:
    tags:
    - '**'

env:
  SAMO_DOCKER_REGISTRY: ghcr.io

jobs:
  build:
    name: build-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: lorislab/install-samo-action@v1             
      - name: Release docker image
        run: samo project docker release -v debug
      - name: Release helm
        run: samo project helm release -v debug          
