name: release
on:
  push:
    tags:
    - '**'

env:
  SAMO_DOCKER_REGISTRY: ghcr.io

jobs:
  build:
    name: build-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.CI_PAT }}
      - name: Release docker image
        uses: lorislab/samo-action@v1.1.0
        with:
          args: samo project docker release -v debug
      - name: Release helm
        uses: lorislab/samo-action@v1.1.0
        with:
          args: samo project helm release -v debug          
