name: release
on:
  push:
    tags:
    - '**'

env:
  SAMO_DOCKER_REGISTRY: ghcr.io
  SAMO_DOCKER_GROUP: ${{ github.repository_owner }}/
  SAMO_HELM_REGISTRY: oci://ghcr.io/${{ github.repository_owner }}/charts
  SAMO_HELM_VALUES_RELEASE_TEMPLATE_LIST: "app.image.tag={{ .Release }},app.version={{ .Release }}"

jobs:
  build:
    name: build-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref_name }}
      - uses: lorislab/install-samo-action@v1      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.SAMO_DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}             
      - name: Release docker image
        run: samo project docker release -v debug
      - name: Release helm
        run: samo project helm release -v debug    
